[phases.setup]
nixPkgs = [
    'php82',
    'php82Packages.composer',
    'php82Extensions.pdo',
    'php82Extensions.pdo_mysql'
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:${PORT} -t ."
healthcheck = "curl -f http://localhost:${PORT}/health" 